# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: 'bluswtr@gmail.com'
GMAIL_PASSWORD: 'Sakura8957!'
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
APP_ID: '559267427470556'
APP_SECRET: 0578ea2d6a4b1d198ce1f6b789ea97d7
STRAVA_ID: '415'
STRAVA_SECRET: c93f98b9d07427b4290e2da6943332cd1ac0967a